#!/usr/bin/env python3
# Copyright (c) 2025 Basalte bv
#
# SPDX-License-Identifier: Apache-2.0

"""
A script to plot data in a sunburst chart generated by size_report.
When you call the ram_report or rom_report targets you end up
with a json file in the build directory that can be used as input
for this script.

Example:
   ./scripts/footprint/plot.py build/ram.json

Requires plotly to be installed, for example with pip:
   pip install plotly
"""

import argparse
import json
import os
import sys
import tempfile
import webbrowser
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        allow_abbrev=False,
    )

    parser.add_argument('input', help='Input json file')
    parser.add_argument('--html', help='Output html file')
    parser.add_argument(
        '--depth',
        help='Maximum render depth, pass -1 to render all levels. Defaults to 4',
        type=int,
        default=4,
    )

    return parser.parse_args()


def main():
    args = parse_args()

    try:
        import plotly.graph_objects as go
    except ImportError:
        sys.exit("Missing dependency: You need to install plotly.")

    with open(args.input) as f:
        data = json.load(f)

    root = data.get('symbols', {})
    totalsize = data.get('total_size') or root.get('size') or 0
    ids = []
    labels = []
    parents = []
    values = []
    hovertext = []

    def iter_leaf_sections(node: dict):
        if not isinstance(node, dict):
            return
        children = node.get('children') or ()
        if children:
            for child in children:
                iter_leaf_sections(child)
            return
        section = node.get('section')
        if section:
            sections.add(section)

    def clone_subtree_for_section(node: dict, section: str):
        if not isinstance(node, dict):
            return None

        children = node.get('children') or ()
        if not children:
            if node.get('section') != section:
                return None
            clone = dict(node)
            identifier = clone.get('identifier')
            if identifier is not None:
                clone['identifier'] = f'{section}|{identifier}'
            return clone

        new_children = []
        for child in children:
            filtered = clone_subtree_for_section(child, section)
            if filtered is not None:
                new_children.append(filtered)

        if not new_children:
            return None

        clone = dict(node)
        identifier = clone.get('identifier')
        if identifier is not None:
            clone['identifier'] = f'{section}|{identifier}'
        clone['children'] = new_children
        clone['size'] = sum(c.get('size', 0) for c in new_children)
        clone.pop('section', None)
        clone.pop('address', None)
        return clone

    def iter_node(node: dict, parent=''):
        identifier = node.get('identifier')
        if identifier is None:
            return

        if identifier in ids:
            # Identifiers aren't unique, add a suffix to make them unique
            idx = 0
            while f'{identifier}_{idx}' in ids:
                idx += 1
            identifier = f'{identifier}_{idx}'

        ids.append(identifier)
        labels.append(node.get('name', ''))
        parents.append(parent)
        values.append(node.get('size', 0))

        node_size = node.get("size", 0)
        pct = (node_size / totalsize) if totalsize else 0.0
        details = [f'percentage: {pct:.2%}']
        if 'address' in node:
            details.append(f'address: 0x{node.get("address"):08x}')
        if 'section' in node:
            details.append(f'section: {node.get("section")}')

        hovertext.append("<br>".join(details))

        for child in node.get('children', ()):
            iter_node(child, identifier)

    sections = set()
    iter_leaf_sections(root)

    if sections:
        section_nodes = []
        for section in sorted(sections):
            children = []
            for child in root.get('children', ()):
                filtered = clone_subtree_for_section(child, section)
                if filtered is not None:
                    children.append(filtered)
            if not children:
                continue
            section_nodes.append(
                {
                    "name": section,
                    "size": sum(c.get('size', 0) for c in children),
                    "identifier": f"section:{section}",
                    "children": children,
                }
            )

        root_for_plot = {
            "name": root.get("name", "Root"),
            "size": sum(c.get('size', 0) for c in section_nodes),
            "identifier": root.get("identifier", "root"),
            "children": section_nodes,
        }
        iter_node(root_for_plot)
    else:
        iter_node(root)

    fig = go.Figure(
        go.Sunburst(
            ids=ids,
            labels=labels,
            parents=parents,
            values=values,
            hovertext=hovertext,
            branchvalues='total',
            maxdepth=args.depth,
        ),
        skip_invalid=True,
    )
    fig.update_layout(margin={'t': 0, 'l': 0, 'r': 0, 'b': 0})

    if args.html:
        fig.write_html(args.html, auto_open=False)
        return

    fd, html_path = tempfile.mkstemp(prefix="zephyr-footprint-", suffix=".html")
    os.close(fd)

    html_path = Path(html_path)
    fig.write_html(html_path, auto_open=False)

    print(f"Wrote plot to {html_path}")
    opened = webbrowser.open(html_path.resolve().as_uri())
    if not opened:
        print(
            f"Failed to open a browser automatically. Open this file manually: {html_path}",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
